name: Unit Test

on: push

jobs:
  ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Run Pester
        shell: pwsh
        run: Invoke-Pester